"""ELLE Setup Wizard.

A friendly, interactive wizard that guides users through initial configuration.
Runs on first launch and can be re-run via /reconfigure or /policies.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from rich.panel import Panel
from rich.text import Text

from elle.cli.setup.models import (
    CONFIRMATION_INFO,
    FEATURE_INFO,
    SAFETY_LEVEL_INFO,
    TELEMETRY_INFO,
    ConfirmationPreference,
    SafetyLevel,
    SetupPreferences,
    SetupState,
)
from elle.cli.ui import (
    Icons,
    bulleted_list,
    console,
    numbered_list,
    option_list,
    print_info,
    print_muted,
    print_success,
    print_warning,
    section_header,
    section_rule,
    tip,
)

if TYPE_CHECKING:
    from elle.cli.ui.prompt import EllePrompt


# Config file paths
USER_CONFIG_DIR = Path.home() / ".config" / "elle"
USER_CONFIG_FILE = USER_CONFIG_DIR / "elle.toml"
USER_POLICY_FILE = USER_CONFIG_DIR / "policy.yaml"

# State marker in config
SETUP_STATE_KEY = "setup"


def is_first_run() -> bool:
    """Check if this is the first time ELLE is being run.

    Returns:
        True if setup wizard should run.
    """
    if not USER_CONFIG_FILE.exists():
        return True

    try:
        import tomllib

        with open(USER_CONFIG_FILE, "rb") as f:
            config = tomllib.load(f)

        setup = config.get("setup", {})
        return not setup.get("completed", False)
    except Exception:
        return True


def load_setup_state() -> SetupState:
    """Load existing setup state from config.

    Returns:
        SetupState with current configuration.
    """
    if not USER_CONFIG_FILE.exists():
        return SetupState()

    try:
        import tomllib

        with open(USER_CONFIG_FILE, "rb") as f:
            config = tomllib.load(f)

        setup_data = config.get("setup", {})
        prefs_data = setup_data.get("preferences", {})

        prefs = SetupPreferences(**prefs_data) if prefs_data else SetupPreferences()

        return SetupState(
            completed=setup_data.get("completed", False),
            completed_at=setup_data.get("completed_at"),
            version=setup_data.get("version", "0.1.0"),
            preferences=prefs,
        )
    except Exception:
        return SetupState()


def save_setup_state(state: SetupState) -> None:
    """Save setup state to config file.

    Args:
        state: The setup state to save.
    """
    import toml

    # Ensure config directory exists
    USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # Load existing config or start fresh
    config: dict = {}
    if USER_CONFIG_FILE.exists():
        try:
            import tomllib

            with open(USER_CONFIG_FILE, "rb") as f:
                config = tomllib.load(f)
        except Exception:
            pass

    # Update setup section
    config["setup"] = {
        "completed": state.completed,
        "completed_at": state.completed_at.isoformat() if state.completed_at else None,
        "version": state.version,
        "preferences": state.preferences.model_dump(),
    }

    # Update daemon section based on preferences
    if "daemon" not in config:
        config["daemon"] = {}

    prefs = state.preferences
    config["daemon"]["journal_enabled"] = prefs.journal_enabled
    config["daemon"]["kernel_enabled"] = prefs.kernel_enabled
    config["daemon"]["probes_enabled"] = prefs.probes_enabled
    config["daemon"]["ebpf_enabled"] = prefs.ebpf_enabled
    config["daemon"]["docker_enabled"] = prefs.docker_enabled

    if "daemon.api" not in config:
        config["daemon"]["api"] = {}
    config["daemon"]["api"]["enabled"] = prefs.api_enabled

    # Write config
    with open(USER_CONFIG_FILE, "w") as f:
        toml.dump(config, f)


def generate_policy_file(prefs: SetupPreferences) -> None:
    """Generate user policy file based on preferences.

    Args:
        prefs: User preferences from setup.
    """
    USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    policy_content = _build_policy_yaml(prefs)

    with open(USER_POLICY_FILE, "w") as f:
        f.write(policy_content)


def _build_policy_yaml(prefs: SetupPreferences) -> str:
    """Build policy YAML content based on preferences.

    Args:
        prefs: User preferences.

    Returns:
        YAML content string.
    """
    lines = [
        "# ELLE Policy Configuration",
        "# Generated by setup wizard",
        f"# Last updated: {datetime.now().isoformat()}",
        "",
        "version: '1.0'",
        "name: User Policy",
        "extends: system:defaults",
        "",
        "# Default effect when no rules match",
    ]

    # Set default effect based on safety level
    if prefs.safety_level == SafetyLevel.CAUTIOUS:
        lines.append("default_effect: REQUIRE_CONFIRMATION")
    elif prefs.safety_level == SafetyLevel.MINIMAL:
        lines.append("default_effect: ALLOW")
    else:
        lines.append("default_effect: ALLOW")

    lines.extend(["", "rules:"])

    # Add confirmation rules based on preference
    if prefs.confirmation_preference == ConfirmationPreference.ALWAYS:
        lines.extend([
            "  - id: confirm-all-tasks",
            "    name: Require confirmation for all tasks",
            "    conditions:",
            "      - intent: system_task",
            "        match_type: exact",
            "    effect: REQUIRE_CONFIRMATION",
            "    message: Please confirm this operation",
            "    priority: 50",
            "",
        ])
    elif prefs.confirmation_preference == ConfirmationPreference.NEVER:
        lines.extend([
            "  - id: skip-confirmation",
            "    name: Skip confirmation for low-risk tasks",
            "    conditions:",
            "      - risk_level: low",
            "        match_type: exact",
            "      - risk_level: medium",
            "        match_type: exact",
            "    effect: ALLOW",
            "    priority: 40",
            "",
        ])

    # Add preview requirement for config changes
    if prefs.require_preview_for_configs:
        lines.extend([
            "  - id: preview-config-changes",
            "    name: Show preview before config changes",
            "    conditions:",
            "      - path: /etc/*",
            "        match_type: glob",
            "    effect: REQUIRE_PREVIEW",
            "    message: Review changes before applying",
            "    priority: 45",
            "",
        ])

    # Add stricter rules for cautious mode
    if prefs.safety_level == SafetyLevel.CAUTIOUS:
        lines.extend([
            "  - id: cautious-service-restart",
            "    name: Confirm service restarts",
            "    conditions:",
            "      - command: systemctl restart*",
            "        match_type: glob",
            "    effect: REQUIRE_CONFIRMATION",
            "    message: Restarting services may cause brief interruptions",
            "    priority: 55",
            "",
            "  - id: cautious-package-install",
            "    name: Confirm package installations",
            "    conditions:",
            "      - command: apt install*",
            "        match_type: glob",
            "    effect: REQUIRE_CONFIRMATION",
            "    message: Review packages before installation",
            "    priority: 55",
            "",
        ])

    return "\n".join(lines)


class SetupWizard:
    """Interactive setup wizard for ELLE.

    Guides users through initial configuration with friendly,
    non-intimidating descriptions of each option.
    """

    def __init__(self, prompt: "EllePrompt") -> None:
        """Initialize the wizard.

        Args:
            prompt: The prompt instance for user interaction.
        """
        self.prompt = prompt
        self.state = load_setup_state()
        self.prefs = self.state.preferences

    def run(self, reconfigure: bool = False) -> bool:
        """Run the setup wizard.

        Args:
            reconfigure: If True, running as reconfiguration (not first run).

        Returns:
            True if setup completed successfully, False if cancelled.
        """
        try:
            if reconfigure:
                self._show_reconfigure_intro()
            else:
                self._show_welcome()

            # Step 1: Check environment
            if not self._check_environment():
                return False

            # Step 2: Safety and confirmation preferences
            if not self._configure_safety():
                return False

            # Step 3: Telemetry sources
            if not self._configure_telemetry():
                return False

            # Step 4: Optional features
            if not self._configure_features():
                return False

            # Step 5: Review and confirm
            if not self._review_and_confirm():
                return False

            # Save configuration
            self._save_configuration()

            self._show_completion()
            return True

        except (KeyboardInterrupt, EOFError):
            console.print()
            print_warning("Setup cancelled. You can run /reconfigure later.")
            return False

    def _show_welcome(self) -> None:
        """Display the welcome message."""
        console.print()
        welcome = Panel(
            Text.from_markup(
                "[bold]Welcome to ELLE[/bold]\n\n"
                "This quick setup will help you configure ELLE for your needs.\n"
                "You can change any of these settings later with [cyan]/reconfigure[/cyan].\n\n"
                "[dim]Press Ctrl+C at any time to skip setup.[/dim]"
            ),
            title="[bold cyan]First-Time Setup[/bold cyan]",
            border_style="cyan",
            padding=(1, 2),
        )
        console.print(welcome)
        console.print()

    def _show_reconfigure_intro(self) -> None:
        """Display intro for reconfiguration."""
        console.print()
        console.print(section_header("ELLE Configuration", icon=Icons.SETTINGS))
        console.print()
        print_muted("Let's update your ELLE settings. Current values are shown as defaults.")
        console.print()

    def _check_environment(self) -> bool:
        """Check the runtime environment and Ollama availability."""
        console.print(section_rule("Environment Check"))
        console.print()

        checks = []

        # Check Python version
        import sys
        py_version = f"{sys.version_info.major}.{sys.version_info.minor}"
        checks.append(f"{Icons.SUCCESS} Python {py_version}")

        # Check for config directory
        if USER_CONFIG_DIR.exists():
            checks.append(f"{Icons.SUCCESS} Config directory exists")
        else:
            checks.append(f"{Icons.INFO} Config directory will be created")

        # Check Ollama
        ollama_status = self._check_ollama()
        if ollama_status["available"]:
            checks.append(f"{Icons.SUCCESS} Ollama is running")
            if ollama_status["models"]:
                model_list = ", ".join(ollama_status["models"][:3])
                checks.append(f"  {Icons.BULLET} Models: {model_list}")
            self.prefs.ollama_verified = True
        else:
            checks.append(f"{Icons.WARNING} Ollama not detected")
            self.prefs.ollama_verified = False

        for check in checks:
            console.print(f"  {check}")

        console.print()

        if not ollama_status["available"]:
            print_warning(
                "ELLE requires Ollama for AI features. Install it from ollama.ai"
            )
            console.print()
            print_muted(
                "You can continue setup, but AI features won't work until Ollama is installed."
            )
            console.print()

            if not self.prompt.prompt_confirm("Continue setup without Ollama?", default=True):
                return False

        return True

    def _check_ollama(self) -> dict:
        """Check if Ollama is available and list models."""
        try:
            import httpx

            response = httpx.get("http://localhost:11434/api/tags", timeout=2.0)
            if response.status_code == 200:
                data = response.json()
                models = [m["name"] for m in data.get("models", [])]
                return {"available": True, "models": models}
        except Exception:
            pass
        return {"available": False, "models": []}

    def _configure_safety(self) -> bool:
        """Configure safety level and confirmation preferences."""
        console.print(section_rule("Safety Settings"))
        console.print()

        # Explain what this section is about
        console.print(
            Text.from_markup(
                "[bold]How should ELLE handle potentially risky operations?[/bold]\n\n"
                "ELLE can block dangerous commands and ask for confirmation before\n"
                "making changes. Choose the level that fits your comfort level."
            )
        )
        console.print()

        # Safety level selection
        console.print("[bold]Safety Level:[/bold]")
        console.print()

        options = []
        for level in SafetyLevel:
            info = SAFETY_LEVEL_INFO[level]
            options.append((level.value, info["name"]))

        console.print(option_list(options))
        console.print()

        # Show descriptions
        for level in SafetyLevel:
            info = SAFETY_LEVEL_INFO[level]
            console.print(f"  [cyan]{level.value}[/cyan]: {info['description']}")
            console.print()

        default_level = self.prefs.safety_level.value
        while True:
            choice = self.prompt.session.prompt(
                f"Choose safety level [{default_level}]: "
            ).strip().lower()

            if not choice:
                choice = default_level

            try:
                self.prefs.safety_level = SafetyLevel(choice)
                break
            except ValueError:
                print_warning(f"Invalid choice: {choice}")

        console.print()

        # Confirmation preference
        console.print("[bold]Confirmation Prompts:[/bold]")
        console.print()

        for pref in ConfirmationPreference:
            info = CONFIRMATION_INFO[pref]
            marker = Icons.CHEVRON if pref == self.prefs.confirmation_preference else "  "
            console.print(f"  {marker} [cyan]{pref.value}[/cyan]: {info['description']}")

        console.print()

        default_conf = self.prefs.confirmation_preference.value
        while True:
            choice = self.prompt.session.prompt(
                f"Choose confirmation preference [{default_conf}]: "
            ).strip().lower()

            if not choice:
                choice = default_conf

            try:
                self.prefs.confirmation_preference = ConfirmationPreference(choice)
                break
            except ValueError:
                print_warning(f"Invalid choice: {choice}")

        console.print()

        # Preview for config changes
        default_preview = "y" if self.prefs.require_preview_for_configs else "n"
        self.prefs.require_preview_for_configs = self.prompt.prompt_confirm(
            "Show preview before modifying config files?",
            default=self.prefs.require_preview_for_configs,
        )

        console.print()
        return True

    def _configure_telemetry(self) -> bool:
        """Configure which telemetry sources to enable."""
        console.print(section_rule("Telemetry Sources"))
        console.print()

        console.print(
            Text.from_markup(
                "[bold]What should ELLE monitor?[/bold]\n\n"
                "ELLE can watch various system sources for issues.\n"
                "All monitoring is local - no data leaves your machine."
            )
        )
        console.print()

        # Journal
        info = TELEMETRY_INFO["journal"]
        self.prefs.journal_enabled = self.prompt.prompt_confirm(
            f"{info['name']}: {info['description']}",
            default=self.prefs.journal_enabled,
        )

        # Kernel
        info = TELEMETRY_INFO["kernel"]
        self.prefs.kernel_enabled = self.prompt.prompt_confirm(
            f"{info['name']}: {info['description']}",
            default=self.prefs.kernel_enabled,
        )

        # Probes
        info = TELEMETRY_INFO["probes"]
        self.prefs.probes_enabled = self.prompt.prompt_confirm(
            f"{info['name']}: {info['description']}",
            default=self.prefs.probes_enabled,
        )

        # Docker
        info = TELEMETRY_INFO["docker"]
        self.prefs.docker_enabled = self.prompt.prompt_confirm(
            f"{info['name']}: {info['description']}",
            default=self.prefs.docker_enabled,
        )

        # eBPF (advanced)
        console.print()
        info = TELEMETRY_INFO["ebpf"]
        console.print(f"  [dim]{info['description']}[/dim]")
        self.prefs.ebpf_enabled = self.prompt.prompt_confirm(
            f"{info['name']} (advanced)",
            default=self.prefs.ebpf_enabled,
        )

        console.print()
        return True

    def _configure_features(self) -> bool:
        """Configure optional features."""
        console.print(section_rule("Optional Features"))
        console.print()

        # REST API
        info = FEATURE_INFO["api"]
        console.print(f"  [dim]{info['description']}[/dim]")
        self.prefs.api_enabled = self.prompt.prompt_confirm(
            f"Enable {info['name']}?",
            default=self.prefs.api_enabled,
        )

        console.print()

        # GUI Automation
        info = FEATURE_INFO["gui_automation"]
        console.print(f"  [dim]{info['description']}[/dim]")
        self.prefs.gui_automation_enabled = self.prompt.prompt_confirm(
            f"Enable {info['name']}?",
            default=self.prefs.gui_automation_enabled,
        )

        console.print()
        return True

    def _review_and_confirm(self) -> bool:
        """Show summary and confirm settings."""
        console.print(section_rule("Review Settings"))
        console.print()

        # Build summary
        safety_info = SAFETY_LEVEL_INFO[self.prefs.safety_level]
        conf_info = CONFIRMATION_INFO[self.prefs.confirmation_preference]

        summary_items = [
            f"Safety: {safety_info['name']}",
            f"Confirmations: {conf_info['name']}",
            f"Config preview: {'Yes' if self.prefs.require_preview_for_configs else 'No'}",
        ]

        telemetry_enabled = []
        if self.prefs.journal_enabled:
            telemetry_enabled.append("Journal")
        if self.prefs.kernel_enabled:
            telemetry_enabled.append("Kernel")
        if self.prefs.probes_enabled:
            telemetry_enabled.append("Probes")
        if self.prefs.docker_enabled:
            telemetry_enabled.append("Docker")
        if self.prefs.ebpf_enabled:
            telemetry_enabled.append("eBPF")

        summary_items.append(f"Telemetry: {', '.join(telemetry_enabled) or 'None'}")

        features_enabled = []
        if self.prefs.api_enabled:
            features_enabled.append("API")
        if self.prefs.gui_automation_enabled:
            features_enabled.append("GUI")

        summary_items.append(f"Features: {', '.join(features_enabled) or 'None'}")

        summary = Panel(
            bulleted_list(summary_items),
            title="[bold]Your Configuration[/bold]",
            border_style="cyan",
            padding=(1, 2),
        )
        console.print(summary)
        console.print()

        return self.prompt.prompt_confirm("Save these settings?", default=True)

    def _save_configuration(self) -> None:
        """Save the configuration to files."""
        # Update state
        self.state.completed = True
        self.state.completed_at = datetime.now()
        self.state.preferences = self.prefs

        # Save to config file
        save_setup_state(self.state)

        # Generate policy file
        generate_policy_file(self.prefs)

    def _show_completion(self) -> None:
        """Show completion message."""
        console.print()
        print_success("Setup complete!")
        console.print()

        next_steps = [
            "Type a question to get started (e.g., 'how much disk space is left?')",
            "Use /help to see available commands",
            "Run /reconfigure to change these settings later",
        ]

        console.print("[bold]Next steps:[/bold]")
        console.print(numbered_list(next_steps))
        console.print()

        if not self.prefs.ollama_verified:
            console.print(tip("Install Ollama from ollama.ai to enable AI features"))
            console.print()


def run_setup_wizard(prompt: "EllePrompt", reconfigure: bool = False) -> bool:
    """Run the setup wizard.

    Args:
        prompt: The prompt instance for user interaction.
        reconfigure: If True, running as reconfiguration.

    Returns:
        True if setup completed successfully.
    """
    wizard = SetupWizard(prompt)
    return wizard.run(reconfigure=reconfigure)
