"""Core data models for ELLE.

Defines the primary data structures used across the system.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel


class TelemetryEvent(BaseModel):
    """A normalized telemetry event from the system.

    Stored in SQLite at /var/lib/elle/elle.db.
    """

    ts: datetime
    source: Literal["journal", "kernel", "probe"]
    severity: Literal["info", "warning", "error", "critical"]
    category: str
    message: str
    raw: dict[str, Any]


class CommandPlan(BaseModel):
    """A verified plan for system modification.

    Generated by the RAG engine, verified locally before presentation.
    All plans follow: Explain -> Plan -> Confirm -> Apply.
    """

    explanation: str
    commands: list[str]
    checks: list[str]
    rollback: list[str]
    risks: list[str]
    requires_privilege: bool


class ExecutionResult(BaseModel):
    """Result of command or plan execution."""

    success: bool
    output: str
    stderr: str | None = None
    exit_code: int | None = None
    plan: CommandPlan | None = None
