"""Forecast-triggered incident handler.

Creates incidents and runs the Agent Loop when forecast triggers fire.
This is the bridge between the reactive engine (forecast triggers) and
the Agent Loop (remediation planning/execution).

When a forecast trigger fires:
1. Create incident report with forecast evidence
2. Run Agent Loop to generate remediation plan
3. If act_now: Execute plan immediately
4. If prepare: Store plan, notify user

All functionality flows through The Spine:
DAEMON (trends) -> SIGNALS (reactive/engine) -> INCIDENT REPORT (this module)
-> AGENT LOOP -> CAPABILITIES -> OUTCOME -> INCIDENT MEMORY
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

if TYPE_CHECKING:
    from elle.daemon.telemetry.trends import Forecast

logger = logging.getLogger(__name__)


# =============================================================================
# Models
# =============================================================================


class RemediationPlan(BaseModel):
    """A remediation plan generated by the Agent Loop.

    Contains the planned approach for addressing a forecast alert,
    which can be stored and executed later.
    """

    model_config = ConfigDict(frozen=True)

    # Identity
    plan_id: str = Field(description="Unique plan identifier")
    incident_id: str = Field(description="Linked incident ID")

    # What triggered this plan
    metric: str = Field(description="Metric that triggered the plan")
    current_value: float = Field(description="Value at time of planning")
    threshold: float = Field(description="Threshold being approached")
    urgency: Literal["prepare", "act_now"] = Field(description="Urgency level")

    # The plan itself
    summary: str = Field(description="Brief summary of the plan")
    cause_description: str | None = Field(
        default=None,
        description="Description of the probable cause",
    )
    steps: tuple[str, ...] = Field(
        default_factory=tuple,
        description="Ordered list of remediation steps",
    )
    capabilities_to_execute: tuple[str, ...] = Field(
        default_factory=tuple,
        description="Capability names that will be executed",
    )

    # Metadata
    generated_by: str = Field(
        default="agent_loop",
        description="What generated this plan",
    )
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in the plan's effectiveness",
    )

    # Execution state
    executed: bool = Field(default=False, description="Whether plan was executed")
    executed_at: datetime | None = Field(default=None)
    execution_result: str | None = Field(default=None)


class ForecastIncidentResult(BaseModel):
    """Result of handling a forecast trigger."""

    model_config = ConfigDict(frozen=True)

    incident_id: str = Field(description="Created/updated incident ID")
    urgency: Literal["prepare", "act_now"] = Field(description="Urgency level")
    plan: RemediationPlan | None = Field(
        default=None,
        description="Generated plan (for 'prepare' urgency)",
    )
    executed: bool = Field(
        default=False,
        description="Whether remediation was executed",
    )
    success: bool = Field(description="Whether handling succeeded")
    error: str | None = Field(default=None, description="Error if failed")


# =============================================================================
# Incident Creation
# =============================================================================


def create_forecast_incident(
    metric: str,
    current_value: float,
    threshold: float,
    time_to_threshold: float | None,
    rate_of_change: float,
    urgency: Literal["prepare", "act_now"],
    confidence: float = 0.5,
) -> dict[str, Any]:
    """Create an incident dict for a forecast trigger.

    Args:
        metric: The metric that triggered (e.g., "disk./.used_pct").
        current_value: Current metric value.
        threshold: Threshold being approached.
        time_to_threshold: Hours until threshold is crossed.
        rate_of_change: Rate of change per hour.
        urgency: The urgency level.
        confidence: Forecast confidence.

    Returns:
        Dict suitable for incident creation.
    """
    import uuid

    incident_id = f"FORECAST-{uuid.uuid4().hex[:8].upper()}"

    # Determine severity based on urgency
    severity = "warning" if urgency == "prepare" else "critical"

    # Extract domain from metric
    domain = metric.split(".")[0] if "." in metric else "system"

    # Build title
    if time_to_threshold is not None:
        time_str = f"{time_to_threshold:.1f}h"
    else:
        time_str = "imminent"

    title = (
        f"Forecast: {metric} projected to reach {threshold} in {time_str}"
        if urgency == "prepare"
        else f"URGENT: {metric} at {current_value:.1f}, {threshold} threshold imminent"
    )

    return {
        "id": incident_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "domain": domain,
        "severity": severity,
        "status": "open",
        "title": title,
        "summary": (
            f"Metric {metric} is currently at {current_value:.1f} and is projected "
            f"to cross the {'warning' if urgency == 'prepare' else 'critical'} "
            f"threshold of {threshold} at a rate of {rate_of_change:.2f}/hour. "
            f"Forecast confidence: {confidence:.0%}."
        ),
        "trigger_source": "forecast",
        "forecast_metric": metric,
        "forecast_urgency": urgency,
        "metrics_json": {
            "metric": metric,
            "current_value": current_value,
            "threshold": threshold,
            "time_to_threshold_hours": time_to_threshold,
            "rate_of_change": rate_of_change,
            "confidence": confidence,
        },
    }


# =============================================================================
# Forecast Handler
# =============================================================================


async def handle_forecast_trigger(
    forecast: Forecast,
    urgency: Literal["prepare", "act_now"],
) -> ForecastIncidentResult:
    """Handle a forecast trigger through The Spine.

    This is the main entry point when a forecast crosses urgency thresholds.

    Flow:
    1. Create incident from forecast evidence
    2. Run Agent Loop to generate/execute remediation
    3. Record outcome to incident memory

    Args:
        forecast: The Forecast that triggered.
        urgency: The urgency level ('prepare' or 'act_now').

    Returns:
        ForecastIncidentResult with incident ID and outcome.
    """
    try:
        # 1. Create incident from forecast
        incident_data = create_forecast_incident(
            metric=forecast.metric,
            current_value=forecast.current_value,
            threshold=(forecast.critical_threshold if urgency == "act_now" else forecast.warning_threshold) or 0.0,
            time_to_threshold=(
                forecast.time_to_critical_hours if urgency == "act_now" else forecast.time_to_warning_hours
            ),
            rate_of_change=forecast.rate_of_change,
            urgency=urgency,
            confidence=forecast.confidence,
        )

        incident_id = incident_data["id"]

        # Store the incident
        try:
            from elle.daemon.incidents.store import create_incident_draft, update_incident

            report = create_incident_draft(
                title=incident_data.get("title", f"Forecast: {forecast.metric}"),
                domain=incident_data.get("domain", "other"),
                severity=incident_data.get("severity", "warning"),
                trigger_source=incident_data.get("trigger_source", "forecast"),
            )
            incident_id = report.incident_id
            incident_data["id"] = incident_id
            update_incident(
                incident_id,
                summary=incident_data.get("summary"),
                outcome=incident_data.get("outcome"),
                metrics=incident_data.get("metrics_json"),
                status=incident_data.get("status"),
            )
        except ImportError:
            logger.warning("Incident store not available, continuing without persistence")
        except Exception as e:
            logger.warning(f"Failed to persist incident: {e}")

        # 2. Run Agent Loop
        if urgency == "prepare":
            # Generate remediation plan
            plan = await _generate_remediation_plan(forecast, incident_id)

            # Store plan in incident
            await _update_incident_with_plan(incident_id, plan)

            # Check if all plan capabilities can auto-run
            can_auto = _check_plan_autonomy(plan.capabilities_to_execute)

            if can_auto and plan.capabilities_to_execute:
                # Auto-execute and notify AFTER
                success, error = await _execute_remediation(forecast, incident_id)
                outcome = "improved" if success else "no_change"

                await _notify_forecast_remediated(
                    forecast,
                    incident_id,
                    outcome,
                    plan_summary=plan.summary,
                    cause_description=plan.cause_description,
                )

                return ForecastIncidentResult(
                    incident_id=incident_id,
                    urgency=urgency,
                    plan=plan,
                    executed=True,
                    success=success,
                    error=error,
                )
            else:
                # Notify user with plan + "Execute Now" action
                await _notify_forecast_warning(
                    forecast,
                    incident_id,
                    plan,
                )

                return ForecastIncidentResult(
                    incident_id=incident_id,
                    urgency=urgency,
                    plan=plan,
                    executed=False,
                    success=True,
                )

        elif urgency == "act_now":
            # Execute remediation immediately
            success, error = await _execute_remediation(forecast, incident_id)

            # Notify after execution
            outcome = "improved" if success else "no_change"
            await _notify_forecast_remediated(
                forecast,
                incident_id,
                outcome,
            )

            return ForecastIncidentResult(
                incident_id=incident_id,
                urgency=urgency,
                plan=None,
                executed=True,
                success=success,
                error=error,
            )

        # Should not reach here
        return ForecastIncidentResult(
            incident_id=incident_id,
            urgency=urgency,
            executed=False,
            success=False,
            error=f"Unknown urgency level: {urgency}",
        )

    except Exception as e:
        logger.exception(f"Failed to handle forecast trigger: {e}")
        return ForecastIncidentResult(
            incident_id="",
            urgency=urgency,
            executed=False,
            success=False,
            error=str(e),
        )


async def _generate_remediation_plan(
    forecast: Forecast,
    incident_id: str,
) -> RemediationPlan:
    """Generate a remediation plan using the Agent Loop.

    This runs the Agent Loop in planning mode - it generates a plan
    but doesn't execute any capabilities.

    Args:
        forecast: The forecast that triggered.
        incident_id: The incident ID for context.

    Returns:
        RemediationPlan with the generated steps.
    """
    import uuid

    try:
        from elle.cli.agentic.loop import AgenticLoop

        # Build the planning query
        query = (
            f"Metric {forecast.metric} is currently at {forecast.current_value:.1f} "
            f"and is projected to breach the warning threshold of {forecast.warning_threshold} "
            f"in {forecast.time_to_warning_hours:.1f} hours. "
            f"Generate a remediation plan to prevent this threshold breach. "
            f"Do NOT execute any capabilities - only plan the remediation steps."
        )

        loop = AgenticLoop(
            prefetch_context=True,
            enable_audit=True,
            enable_verification=False,  # Planning only
        )

        # Run in planning mode
        result = await loop.run(query)

        # Parse the response into a plan
        # The response should contain the plan steps
        steps = _parse_plan_steps(result.response)

        # Extract mentioned capabilities
        capabilities = _extract_capabilities(result.response)

        # Extract cause description from response
        cause_description = _extract_cause_description(result.response)

        return RemediationPlan(
            plan_id=uuid.uuid4().hex,
            incident_id=incident_id,
            metric=forecast.metric,
            current_value=forecast.current_value,
            threshold=forecast.warning_threshold or 0.0,
            urgency="prepare",
            summary=_extract_summary(result.response),
            cause_description=cause_description,
            steps=tuple(steps),
            capabilities_to_execute=tuple(capabilities),
            confidence=forecast.confidence,
            generated_at=datetime.now(timezone.utc),
        )

    except Exception as e:
        logger.exception(f"Failed to generate remediation plan: {e}")
        # Return a minimal plan with the error
        return RemediationPlan(
            plan_id=uuid.uuid4().hex,
            incident_id=incident_id,
            metric=forecast.metric,
            current_value=forecast.current_value,
            threshold=forecast.warning_threshold or 0.0,
            urgency="prepare",
            summary=f"Failed to generate plan: {e}",
            steps=(),
            capabilities_to_execute=(),
            confidence=0.0,
            generated_at=datetime.now(timezone.utc),
        )


async def _execute_remediation(
    forecast: Forecast,
    incident_id: str,
) -> tuple[bool, str | None]:
    """Execute remediation using the Agent Loop.

    This runs the Agent Loop in execution mode - it can execute
    capabilities to address the issue.

    Args:
        forecast: The forecast that triggered.
        incident_id: The incident ID for context.

    Returns:
        Tuple of (success, error_message).
    """
    try:
        from elle.cli.agentic.loop import AgenticLoop

        # Build the execution query
        query = (
            f"URGENT: Metric {forecast.metric} is at {forecast.current_value:.1f}, "
            f"projected to breach critical threshold of {forecast.critical_threshold} "
            f"in {forecast.time_to_critical_hours:.1f} hours. "
            f"Execute remediation immediately to prevent system impact."
        )

        loop = AgenticLoop(
            prefetch_context=True,
            enable_audit=True,
            enable_verification=True,
        )

        result = await loop.run(query)

        # Update incident with outcome
        await _update_incident_outcome(
            incident_id,
            success=result.success,
            response=result.response,
        )

        return result.success, result.error

    except Exception as e:
        logger.exception(f"Failed to execute remediation: {e}")
        return False, str(e)


async def _update_incident_with_plan(
    incident_id: str,
    plan: RemediationPlan,
) -> None:
    """Update an incident with the prepared plan.

    Args:
        incident_id: The incident ID.
        plan: The remediation plan.
    """

    try:
        from elle.daemon.incidents.store import update_incident

        update_incident(
            incident_id,
            metrics={"prepared_plan": plan.model_dump(mode="json")},
        )
    except ImportError:
        logger.debug("Incident store not available")
    except Exception as e:
        logger.warning(f"Failed to update incident with plan: {e}")


async def _update_incident_outcome(
    incident_id: str,
    success: bool,
    response: str,
) -> None:
    """Update an incident with the execution outcome.

    Args:
        incident_id: The incident ID.
        success: Whether execution succeeded.
        response: The agent's response.
    """
    try:
        from elle.daemon.incidents.store import update_incident

        outcome = "improved" if success else "no_change"
        status = "mitigated" if success else "open"

        update_incident(
            incident_id,
            outcome=outcome,
            status=status,
            metrics={"plan_executed_at": datetime.now(timezone.utc).isoformat()},
        )
    except ImportError:
        logger.debug("Incident store not available")
    except Exception as e:
        logger.warning(f"Failed to update incident outcome: {e}")


# =============================================================================
# Autonomy & Notification Helpers
# =============================================================================


def _check_plan_autonomy(capabilities: tuple[str, ...]) -> bool:
    """Check if ALL capabilities in the plan can run autonomously.

    Args:
        capabilities: Tuple of capability names from the plan.

    Returns:
        True if all capabilities can auto-run, False if any require confirmation.
    """
    if not capabilities:
        return False

    try:
        from elle.capabilities.autonomy import get_autonomy_engine
        from elle.capabilities.registry import get_registry

        engine = get_autonomy_engine()
        registry = get_registry()

        for cap_name in capabilities:
            capability = registry.get(cap_name)
            if capability is None:
                # Unknown capability - can't auto-run
                return False

            can_auto, _reason = engine.can_run_autonomously(cap_name, capability.spec.risk)
            if not can_auto:
                return False

        return True

    except ImportError:
        logger.debug("Autonomy engine not available")
        return False
    except Exception as e:
        logger.warning(f"Autonomy check failed: {e}")
        return False


async def _notify_forecast_warning(
    forecast: Forecast,
    incident_id: str,
    plan: RemediationPlan,
) -> None:
    """Send pre-execution notification with plan details.

    Args:
        forecast: The forecast that triggered.
        incident_id: The incident ID.
        plan: The generated remediation plan.
    """
    try:
        from elle.daemon.notifications.service import notify_forecast

        threshold = forecast.warning_threshold or 0.0

        notify_forecast(
            metric=forecast.metric,
            current_value=forecast.current_value,
            threshold=threshold,
            time_to_threshold_hours=forecast.time_to_warning_hours,
            incident_id=incident_id,
            plan_summary=plan.summary,
            cause_description=plan.cause_description,
            auto_remediated=False,
        )
    except Exception as e:
        logger.warning(f"Failed to send forecast warning notification: {e}")


async def _notify_forecast_remediated(
    forecast: Forecast,
    incident_id: str,
    outcome: str,
    plan_summary: str | None = None,
    cause_description: str | None = None,
) -> None:
    """Send post-execution notification with outcome.

    Args:
        forecast: The forecast that triggered.
        incident_id: The incident ID.
        outcome: The remediation outcome.
        plan_summary: Summary of the plan that was executed.
        cause_description: Description of the cause.
    """
    try:
        from elle.daemon.notifications.service import notify_forecast

        threshold = forecast.critical_threshold or forecast.warning_threshold or 0.0

        notify_forecast(
            metric=forecast.metric,
            current_value=forecast.current_value,
            threshold=threshold,
            time_to_threshold_hours=forecast.time_to_warning_hours,
            incident_id=incident_id,
            plan_summary=plan_summary,
            cause_description=cause_description,
            auto_remediated=True,
            outcome=outcome,
        )
    except Exception as e:
        logger.warning(f"Failed to send forecast remediated notification: {e}")


async def execute_prepared_plan(incident_id: str) -> ForecastIncidentResult:
    """Execute a previously prepared plan (triggered by user action).

    Loads the prepared plan from the incident store and runs the
    Agent Loop in execution mode.

    Args:
        incident_id: The incident ID with a prepared plan.

    Returns:
        ForecastIncidentResult with execution outcome.
    """
    try:
        from elle.daemon.incidents.store import get_prepared_plan

        plan_data = get_prepared_plan(incident_id)
        if not plan_data:
            return ForecastIncidentResult(
                incident_id=incident_id,
                urgency="prepare",
                executed=False,
                success=False,
                error="No prepared plan found for this incident",
            )

        plan = RemediationPlan(**plan_data)

        # Build execution query from the plan
        from elle.cli.agentic.loop import AgenticLoop

        steps_text = "\n".join(f"- {step}" for step in plan.steps)
        query = (
            f"Execute the following remediation plan for metric {plan.metric} "
            f"(current: {plan.current_value:.1f}, threshold: {plan.threshold}):\n"
            f"{steps_text}\n"
            f"Execute the required capabilities to address this issue."
        )

        loop = AgenticLoop(
            prefetch_context=True,
            enable_audit=True,
            enable_verification=True,
        )

        result = await loop.run(query)

        # Update incident outcome
        await _update_incident_outcome(
            incident_id,
            success=result.success,
            response=result.response,
        )

        # Send post-execution notification
        outcome = "improved" if result.success else "no_change"
        try:
            from elle.daemon.notifications.service import notify_forecast

            notify_forecast(
                metric=plan.metric,
                current_value=plan.current_value,
                threshold=plan.threshold,
                time_to_threshold_hours=None,
                incident_id=incident_id,
                plan_summary=plan.summary,
                cause_description=plan.cause_description,
                auto_remediated=True,
                outcome=outcome,
            )
        except Exception as e:
            logger.warning(f"Failed to send post-execution notification: {e}")

        return ForecastIncidentResult(
            incident_id=incident_id,
            urgency="prepare",
            plan=plan,
            executed=True,
            success=result.success,
            error=result.error,
        )

    except Exception as e:
        logger.exception(f"Failed to execute prepared plan: {e}")
        return ForecastIncidentResult(
            incident_id=incident_id,
            urgency="prepare",
            executed=False,
            success=False,
            error=str(e),
        )


# =============================================================================
# Response Parsing Helpers
# =============================================================================


def _parse_plan_steps(response: str) -> list[str]:
    """Parse plan steps from the agent's response.

    Looks for numbered lists or bullet points.

    Args:
        response: The agent's response text.

    Returns:
        List of plan steps.
    """
    import re

    steps = []

    # Look for numbered steps
    numbered = re.findall(r"^\d+\.\s+(.+)$", response, re.MULTILINE)
    if numbered:
        steps.extend(numbered)

    # Look for bullet points
    bullets = re.findall(r"^[-*]\s+(.+)$", response, re.MULTILINE)
    if bullets and not numbered:
        steps.extend(bullets)

    return steps if steps else ["See response for details"]


def _extract_capabilities(response: str) -> list[str]:
    """Extract capability names mentioned in the response.

    Args:
        response: The agent's response text.

    Returns:
        List of capability names.
    """
    import re

    # Look for capability patterns like "service.restart", "file.write", etc.
    pattern = r"\b([a-z]+\.[a-z_]+)\b"
    capabilities = set(re.findall(pattern, response.lower()))

    # Filter to known capability prefixes
    known_prefixes = {"service", "file", "config", "docker", "package", "network"}
    return [c for c in capabilities if c.split(".")[0] in known_prefixes]


def _extract_summary(response: str) -> str:
    """Extract a summary from the agent's response.

    Takes the first paragraph or first 200 characters.

    Args:
        response: The agent's response text.

    Returns:
        Summary string.
    """
    # Take first paragraph
    paragraphs = response.split("\n\n")
    if paragraphs:
        summary = paragraphs[0].strip()
        if len(summary) > 200:
            summary = summary[:197] + "..."
        return summary
    return response[:200] if len(response) > 200 else response


def _extract_cause_description(response: str) -> str | None:
    """Extract cause/reason from Agent Loop response.

    Looks for common patterns like "Cause:", "Root cause:", "Reason:",
    "This is likely due to", etc.

    Args:
        response: The agent's response text.

    Returns:
        Cause description, or None if not found.
    """
    import re

    # Look for explicit cause labels
    patterns = [
        r"(?:root\s+)?cause[:\s]+(.+?)(?:\n|$)",
        r"reason[:\s]+(.+?)(?:\n|$)",
        r"(?:this\s+is\s+)?(?:likely\s+)?(?:due\s+to|caused\s+by)[:\s]+(.+?)(?:\n|$)",
        r"problem[:\s]+(.+?)(?:\n|$)",
    ]

    for pattern in patterns:
        match = re.search(pattern, response, re.IGNORECASE)
        if match:
            cause = match.group(1).strip()
            if len(cause) > 120:
                cause = cause[:117] + "..."
            if len(cause) > 10:  # Skip very short matches
                return cause

    return None
